AllCops:
  Include:
    - chef-handler-datadog.gemspec
    - '**/Appraisals'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'spec/*.rb'
    - '*/vendor/**/*'

# Remove RequiredRubyVersion check, it necessarily fails in CI as we test
# with different ruby versions.
Gemspec/RequiredRubyVersion:
  Enabled: false

# 80 characters is a nice goal, but not worth currently changing in existing
# code for the sake of changing it to conform to a length set in 1928 (IBM).
Metrics/LineLength:
  Max: 150

#####
# These exceptions are good goals to attain, and probably will over time,
# so periodic disabling and re-running to inspect values is suggested.

# TODO: main method `report` does a lot of work, which drives this number up.
Metrics/AbcSize:
  Max: 38

# TODO: Main class is currently over 100 lines of code, making comprehending
# it harder. With refactors and simplifications, we can bring this down,
# but for now, let's not make it too much worse.
Metrics/ClassLength:
  Max: 158

# TODO: this is currently down to 7 from 22, and should be a constant
# goal to reduce method complexity. The accepted goal is 6.
# Method `select_hostname`
Metrics/CyclomaticComplexity:
  Max: 7

# TODO: The main method `report` is now down from 85 lines. As refactors
# continue, this should drop. However, the goal of 10 lines in a method may
# be a little lofty.
Metrics/MethodLength:
  Max: 36

# TODO: select_hostname, report are both higher than the default of 7
Metrics/PerceivedComplexity:
  Max: 9
