---
http_interactions:
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.run.success","points":[[1578321201,1.0]],"type":"counter","host":"chef.handler.datadog.test-ec2","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:17 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:21 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.run.failure","points":[[1578321201,0.0]],"type":"counter","host":"chef.handler.datadog.test-ec2","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:17 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:21 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.resources.total","points":[[1578321201,0.0]],"type":"gauge","host":"chef.handler.datadog.test-ec2","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:17 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:21 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.resources.updated","points":[[1578321201,0.0]],"type":"gauge","host":"chef.handler.datadog.test-ec2","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:18 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:21 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.resources.elapsed_time","points":[[1578321201,5.0]],"type":"gauge","host":"chef.handler.datadog.test-ec2","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:18 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:21 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/events?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"msg_text":"Chef updated 0 resources out of 0 resources total.","date_happened":1578321201,"msg_title":"Chef
        completed in 5 seconds on chef.handler.datadog.test-ec2 ","priority":"low","parent":null,"tags":["env:testing"],"aggregation_key":"chef.handler.datadog.test-ec2","alert_type":"success","event_type":"config_management.run","source_type_name":"chef","title":"Chef
        completed in 5 seconds on chef.handler.datadog.test-ec2 ","text":"Chef updated
        0 resources out of 0 resources total.","host":"chef.handler.datadog.test-ec2","device":null}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:18 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '356'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status":"ok","event":{"id":5269024486655155046,"title":"Chef completed
        in 5 seconds on chef.handler.datadog.test-ec2 ","text":"Chef updated 0 resources
        out of 0 resources total.","date_happened":1578321201,"handle":null,"priority":"low","related_event_id":null,"tags":["env:testing"],"url":"https://app.datadoghq.com/event/event?id=5269024486655155046"}}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:21 GMT
- request:
    method: put
    uri: https://app.datadoghq.com/api/v1/tags/hosts/chef.handler.datadog.test-ec2?source=chef
    body:
      encoding: UTF-8
      string: '{"tags":["env:testing"]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Dd-Api-Key:
      - "<API_KEY>"
      Dd-Application-Key:
      - "<APPLICATION_KEY>"
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:19 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '63'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Debug:
      - pxuY3ZnSwE+rCP/MLubWk3EuAMlxxciIsQ2EBSRxZafCu9H4+UEVULDCm144bb3W
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"host":"chef.handler.datadog.test-ec2","tags":["env:testing"]}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:21 GMT
recorded_with: VCR 5.0.0
