---
http_interactions:
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.run.success","points":[[1578321206,1.0]],"type":"counter","host":"i-123456","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:22 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:26 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.run.failure","points":[[1578321206,0.0]],"type":"counter","host":"i-123456","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:22 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:26 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.resources.total","points":[[1578321206,0.0]],"type":"gauge","host":"i-123456","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:22 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:26 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.resources.updated","points":[[1578321206,0.0]],"type":"gauge","host":"i-123456","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:23 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:26 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/series?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"series":[{"metric":"chef.resources.elapsed_time","points":[[1578321206,5.0]],"type":"gauge","host":"i-123456","device":null}]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:23 GMT
      Content-Type:
      - text/json
      Content-Length:
      - '16'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status": "ok"}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:26 GMT
- request:
    method: post
    uri: https://app.datadoghq.com/api/v1/events?api_key=<API_KEY>
    body:
      encoding: UTF-8
      string: '{"msg_text":"Chef updated 0 resources out of 0 resources total.","date_happened":1578321206,"msg_title":"Chef
        completed in 5 seconds on i-123456 ","priority":"low","parent":null,"tags":["env:testing"],"aggregation_key":"i-123456","alert_type":"success","event_type":"config_management.run","source_type_name":"chef","title":"Chef
        completed in 5 seconds on i-123456 ","text":"Chef updated 0 resources out
        of 0 resources total.","host":"i-123456","device":null}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/json
  response:
    status:
      code: 202
      message: Accepted
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:23 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '335'
      Connection:
      - keep-alive
      Dd-Pool:
      - propjoe
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"status":"ok","event":{"id":5269024571821786671,"title":"Chef completed
        in 5 seconds on i-123456 ","text":"Chef updated 0 resources out of 0 resources
        total.","date_happened":1578321206,"handle":null,"priority":"low","related_event_id":null,"tags":["env:testing"],"url":"https://app.datadoghq.com/event/event?id=5269024571821786671"}}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:26 GMT
- request:
    method: put
    uri: https://app.datadoghq.com/api/v1/tags/hosts/i-123456?source=chef
    body:
      encoding: UTF-8
      string: '{"tags":["env:testing"]}'
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Dd-Api-Key:
      - "<API_KEY>"
      Dd-Application-Key:
      - "<APPLICATION_KEY>"
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Mon, 06 Jan 2020 14:33:24 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '42'
      Connection:
      - keep-alive
      Pragma:
      - no-cache
      Cache-Control:
      - no-cache
      X-Dd-Debug:
      - sg8vzlrAXfi82gDuSEBUxkn5dG85uDtr4RhaVLNn521TM8s6JdimiKDHvX2NhFjo
      Dd-Pool:
      - dogweb
      Content-Security-Policy:
      - frame-ancestors 'self'; report-uri https://api.datadoghq.com/csp-report
      X-Frame-Options:
      - SAMEORIGIN
      X-Content-Type-Options:
      - nosniff
      Strict-Transport-Security:
      - max-age=15724800;
    body:
      encoding: UTF-8
      string: '{"host":"i-123456","tags":["env:testing"]}'
    http_version: 
  recorded_at: Mon, 06 Jan 2020 14:33:26 GMT
recorded_with: VCR 5.0.0
